spring:
  application:
    name: freshguard-admin-api

server:
  port: 8080

freshguard:
  jwt:
    secret: "ChangeMeInProduction_UseLongRandomSecretKeyForHS256AlgorithmMinimum256Bits"
    expiration-ms: 86400000

logging:
  level:
    org.springframework.security: INFO
